### ISSUE TITLE
[~11/26] 팀블로그 기초 공사

### ISSUE THREAD

**Issue by Queue-ri** [teamcors/teamcors.github.io#1]
## Todo 1: @nusuy 
- [x] 폰트 적용하기 (예~쁜걸로 부탁해용🙃)
- [x] Footer 수정
- [x] Favicon 수정

## Todo 2: @Queue-ri 
- [x] main 브랜치에 배포된거 deploy로 옮기고 main은 복구하기
- [x] 네비게이션 `sticky`하게 수정하기

## Todo 3: @hyojeongchoi 
- ~~카드 내용 부분을 썸네일로 수정하기~~ **(extended to #2 )**
    - 카드의 `height`가 조금 길어져도 썸네일 비율은 6:4 정도 되게끔

## Todo 4: @chaeeun-Han 
- [x] 네비게이션 순서를 ABOUT, POST, CATEGORY가 되도록 수정하기
    - 카테고리는 태그 페이지임
    - contact 삭제

**Comment by Queue-ri** [comment]
Todo 4는 165c257 에서 내가 해버림🙄
