### ISSUE TITLE
[~3/13] 팀블로그 기초공사2

### ISSUE THREAD

**Issue by Queue-ri** [teamcors/teamcors.github.io#4]
## Todo 1: @nusuy 
- [x] about 페이지 수정 - 나름의 아이디어를 기대할게요~

## Todo 2: @hyojeongchoi 
- [x] 헤더 수정: 팀명(풀어서), 캐치프레이즈

## Todo 3: @chaeeun-Han 
- [x] 포스트 가로 영역 wide하게 수정 (단, 근본 있는 사이즈로)

## Todo 4: @Queue-ri 
- [x] about 페이지와 헤더의 스타일 및 이미지 수정
